# Generated by Django 5.0.2 on 2024-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned_qr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
