# Generated by Django 4.1.7 on 2024-03-03 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("setup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                default=uuid.UUID("4ab45af1-1338-450f-ade1-871e24d643e8"),
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
