# Generated by Django 4.1.7 on 2024-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0002_event_event_code_alter_event_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                default="b1f03f6e-d27b-4675-a0e7-7673b6f1ddf5",
                max_length=12,
                unique=True,
            ),
        ),
    ]
