# Generated by Django 4.1.7 on 2024-03-03 13:32

from django.db import migrations, models
import setup.models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0003_alter_event_event_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                default=setup.models.event.generate_unique_value,
                max_length=12,
                unique=True,
            ),
        ),
    ]
